---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adminer
  name: adminer-dp
  labels:
    app: adminer
    comp: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
      comp: adminer
  template:
    metadata:
      labels:
        app: adminer
        comp: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.8.1
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: "db-svc"
          ports:
            - containerPort: 8080
