---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  namespace: adminer
  labels:
    app: adminer
    comp: adminer
spec:
  selector:
    app: adminer
    comp: adminer
  type: ClusterIP
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
