---
apiVersion: v1
kind: Service
metadata:
  name: adminer-svc
  labels:
    component: adminer
spec:
  selector:
    component: adminer
  type: ClusterIP
  ports:
    - name: tcp-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
